# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT license.

[workspace]

members = [
  "common",
  "common-test",
  "proto",
  "dtdl-parser",
  "in-vehicle-digital-twin",
  "samples/command/consumer",
  "samples/command/provider",
  "samples/mixed/consumer",
  "samples/mixed/provider",
  "samples/property/consumer",
  "samples/property/provider"
]