blank_issues_enabled: true
contact_links:
  - name: Backlog Item with acceptance criteria
    url: https://github.com/eclipse-ibeji/ibeji/blob/main/.github/ISSUE_TEMPLATE/backlog-item.md
    about: Please ask and answer questions here.
  - name: Create a report to help us improve
    url: https://github.com/eclipse-ibeji/ibeji/blob/main/.github/ISSUE_TEMPLATE/bug-report.md
    about: Please ask and answer questions here.
