# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT license.

[package]
name = "ibeji-common_test"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
log = "0.4.17"