[package]
authors = ["Michal Bohdal <michal.bohdal@mobica.com>"]
build = "build.rs"
name = "led_driver"
version = "0.1.0"

[build-dependencies]
bindgen = "0.69.4"
cc = { workspace = true }
init_array = { workspace = true }
